server:
  port: 7236
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on
spring:
  data:
    redis:
      host: 47.101.154.34
      port: 6379
      password: "!ABabcd720210"
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  # 数据库链接配置
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        #主数据库
        master:
          name: data_bank
          url: jdbc:mysql://47.121.211.82:3306/data_bank?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
          username: data_bank
          password: xxsWMKSkDGfhTRW7
          driver-class-name: com.mysql.cj.jdbc.Driver

#  rabbitmq:
#    host: 124.220.152.117
#    port: 5672
#    username: admin
#    password: passwd
#    virtual-host: /
#    queue-name: queueWithImage
#    listener:
#      simple:
#        prefetch: 1
logging:
  level:
    com.example.demo.mapper: DEBUG


# 开启分页支持




